### ISSUE TITLE
Adding CONTRIBUTING.md and CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by LitZeus** [yashksaini-coder/SolShare-Social-Media-DApp#1]
Adding both, CONTRIBUTING.md and CODE_OF_CONDUCT.md, will increase the documentation quality and the eventually the project quality

**Comment by LitZeus** [comment]
@yashksaini-coder  can you add the label of `gssoc-ext` please?

**Comment by yashksaini-coder** [comment]
@LitZeus bro this project is  removed from gssoc

**Comment by LitZeus** [comment]
@yashksaini-coder Oh okay, still I will be completing the tasks bro! 😄
