### ISSUE TITLE
[FEATURE] Adding a Workflow for greetings to new issue and PRs

### ISSUE THREAD

**Issue by aditiverma-21** [yashksaini-coder/SolShare-Social-Media-DApp#16]
This workflow runs whenever a new issue or pull request is opened.
Greet User: It uses the actions-ecosystem/action-create-comment action to post a customized comment directly on the issue or pull request.
Personalized Message: The message greets the user by username and dynamically adjusts based on whether it’s an issue or pull request. It also includes a link to the contribution guidelines for new contributors.
**Benefits of the Greeting Workflow**
- Improves User Experience
- Encourages Quality Contributions
- Reduces Common Questions

**Comment by aditiverma-21** [comment]
Hello @yashksaini-coder please add gssoc ext and level labels

**Comment by yashksaini-coder** [comment]
> Hello @yashksaini-coder please add gssoc ext and level labels

this project is not in gssoc-ext
