### ISSUE TITLE
Adding github-actions bot to greet people after they raise an issue or PR

### ISSUE THREAD

**Issue by LitZeus** [yashksaini-coder/SolShare-Social-Media-DApp#2]
### Adding a greet github action bot to greet them and appreciate them will make them feel listened and more eager to work on the other issue and make this app great!

**Comment by yashksaini-coder** [comment]
make one that tags user if possible @LitZeus

**Comment by LitZeus** [comment]
@yashksaini-coder Sure!

@yashksaini-coder  can you add the label of `gssoc-ext` and `level 2` please?

**Comment by yashksaini-coder** [comment]
@LitZeus bro this project is  removed from gssoc
