### ISSUE TITLE
Adding an issue and PR template

### ISSUE THREAD

**Issue by LitZeus** [yashksaini-coder/SolShare-Social-Media-DApp#3]
- Keeping a template for the issue and PR will make it easier to to look into the issues and what exactly is the issue and PR about
- Overall experience will be good!

**Comment by LitZeus** [comment]
@yashksaini-coder  can you add the label of `gssoc-ext` please?

**Comment by yashksaini-coder** [comment]
@LitZeus bro this project is  removed from gssoc
